name: Deploy to Prod

on:
  push:
    branches:
      - dev  # Trigger when changes are pushed to dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config user.name "Your GitHub Username"
        git config user.email "your-email@example.com"

    - name: Checkout prod branch
      run: |
        git fetch origin
        git checkout prod

    - name: Merge dev into prod
      run: |
        git merge origin/dev --allow-unrelated-histories

    - name: Push changes to prod branch
      run: |
        git push origin prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
