name: Auto-Merge Dev Changes

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all branches are fetched
      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Step 3: Merge dev into uat
      - name: Merge Dev into UAT
        run: |
          git checkout uat
          git merge dev --no-ff -m "Auto-merge changes from dev to uat"
          git push origin uat

      # Step 4: Merge dev into prod
      - name: Merge Dev into Prod
        run: |
          git checkout prod
          git merge dev --no-ff -m "Auto-merge changes from dev to prod"
          git push origin prod

      # Step 5: Merge dev into main
      # Step 3: Fetch all branches
      - name: Fetch All Branches
        run: git fetch --all

      # Step 4: Merge dev into uat
      - name: Merge Dev into UAT
        run: |
          git checkout uat
          git merge dev --no-ff -m "Auto-merge changes from dev to uat"
          git push origin uat

      # Step 5: Merge dev into prod
      - name: Merge Dev into Prod
        run: |
          git checkout prod
          git merge dev --no-ff -m "Auto-merge changes from dev to prod"
          git push origin prod

      # Step 6: Merge dev into main
      - name: Merge Dev into Main
        run: |
          git checkout main
          git merge dev --no-ff -m "Auto-merge changes from dev to main"
          git push origin main
